/* magpie: autogenerated */

#ifndef MAGPIE_NATIVE_H
#define MAGPIE_NATIVE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void hello(void);

#endif  /* MAGPIE_NATIVE_H */
